<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Seed the standard 195 sovereign states and their primary currencies.
     */
    public function run(): void
    {
        $countries = [
            ['Afghanistan', '+93', 'Afghan afghani', 'AFN', '؋', 2],
            ['Albania', '+355', 'Albanian lek', 'ALL', 'L', 2],
            ['Algeria', '+213', 'Algerian dinar', 'DZD', 'د.ج', 2],
            ['Andorra', '+376', 'Euro', 'EUR', '€', 2],
            ['Angola', '+244', 'Angolan kwanza', 'AOA', 'Kz', 2],
            ['Antigua and Barbuda', '+1268', 'Eastern Caribbean dollar', 'XCD', '$', 2],
            ['Argentina', '+54', 'Argentine peso', 'ARS', '$', 2],
            ['Armenia', '+374', 'Armenian dram', 'AMD', '֏', 2],
            ['Australia', '+61', 'Australian dollar', 'AUD', '$', 2],
            ['Austria', '+43', 'Euro', 'EUR', '€', 2],
            ['Azerbaijan', '+994', 'Azerbaijani manat', 'AZN', '₼', 2],
            ['Bahamas', '+1242', 'Bahamian dollar', 'BSD', '$', 2],
            ['Bahrain', '+973', 'Bahraini dinar', 'BHD', '.د.ب', 3],
            ['Bangladesh', '+880', 'Bangladeshi taka', 'BDT', '৳', 2],
            ['Barbados', '+1246', 'Barbadian dollar', 'BBD', '$', 2],
            ['Belarus', '+375', 'Belarusian ruble', 'BYN', 'Br', 2],
            ['Belgium', '+32', 'Euro', 'EUR', '€', 2],
            ['Belize', '+501', 'Belize dollar', 'BZD', '$', 2],
            ['Benin', '+229', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Bhutan', '+975', 'Bhutanese ngultrum', 'BTN', 'Nu.', 2],
            ['Bolivia', '+591', 'Bolivian boliviano', 'BOB', 'Bs.', 2],
            ['Bosnia and Herzegovina', '+387', 'Bosnia and Herzegovina convertible mark', 'BAM', 'KM', 2],
            ['Botswana', '+267', 'Botswana pula', 'BWP', 'P', 2],
            ['Brazil', '+55', 'Brazilian real', 'BRL', 'R$', 2],
            ['Brunei', '+673', 'Brunei dollar', 'BND', '$', 2],
            ['Bulgaria', '+359', 'Euro', 'EUR', '€', 2],
            ['Burkina Faso', '+226', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Burundi', '+257', 'Burundian franc', 'BIF', 'Fr', 0],
            ['Cambodia', '+855', 'Cambodian riel', 'KHR', '៛', 2],
            ['Cameroon', '+237', 'Central African CFA franc', 'XAF', 'Fr', 0],
            ['Canada', '+1', 'Canadian dollar', 'CAD', '$', 2],
            ['Cape Verde', '+238', 'Cape Verdean escudo', 'CVE', 'Esc', 2],
            ['Central African Republic', '+236', 'Central African CFA franc', 'XAF', 'Fr', 0],
            ['Chad', '+235', 'Central African CFA franc', 'XAF', 'Fr', 0],
            ['Chile', '+56', 'Chilean peso', 'CLP', '$', 0],
            ['China', '+86', 'Chinese yuan', 'CNY', '¥', 2],
            ['Colombia', '+57', 'Colombian peso', 'COP', '$', 2],
            ['Comoros', '+269', 'Comorian franc', 'KMF', 'Fr', 0],
            ['Congo', '+242', 'Central African CFA franc', 'XAF', 'Fr', 0],
            ['Costa Rica', '+506', 'Costa Rican colón', 'CRC', '₡', 2],
            ['Croatia', '+385', 'Euro', 'EUR', '€', 2],
            ['Cuba', '+53', 'Cuban peso', 'CUP', '$', 2],
            ['Cyprus', '+357', 'Euro', 'EUR', '€', 2],
            ['Czechia', '+420', 'Czech koruna', 'CZK', 'Kč', 2],
            ['DR Congo', '+243', 'Congolese franc', 'CDF', 'FC', 2],
            ['Denmark', '+45', 'Danish krone', 'DKK', 'kr', 2],
            ['Djibouti', '+253', 'Djiboutian franc', 'DJF', 'Fr', 0],
            ['Dominica', '+1767', 'Eastern Caribbean dollar', 'XCD', '$', 2],
            ['Dominican Republic', '+1809', 'Dominican peso', 'DOP', '$', 2],
            ['Ecuador', '+593', 'United States dollar', 'USD', '$', 2],
            ['Egypt', '+20', 'Egyptian pound', 'EGP', '£', 2],
            ['El Salvador', '+503', 'United States dollar', 'USD', '$', 2],
            ['Equatorial Guinea', '+240', 'Central African CFA franc', 'XAF', 'Fr', 0],
            ['Eritrea', '+291', 'Eritrean nakfa', 'ERN', 'Nfk', 2],
            ['Estonia', '+372', 'Euro', 'EUR', '€', 2],
            ['Eswatini', '+268', 'Swazi lilangeni', 'SZL', 'L', 2],
            ['Ethiopia', '+251', 'Ethiopian birr', 'ETB', 'Br', 2],
            ['Fiji', '+679', 'Fijian dollar', 'FJD', '$', 2],
            ['Finland', '+358', 'Euro', 'EUR', '€', 2],
            ['France', '+33', 'Euro', 'EUR', '€', 2],
            ['Gabon', '+241', 'Central African CFA franc', 'XAF', 'Fr', 0],
            ['Gambia', '+220', 'dalasi', 'GMD', 'D', 2],
            ['Georgia', '+995', 'lari', 'GEL', '₾', 2],
            ['Germany', '+49', 'Euro', 'EUR', '€', 2],
            ['Ghana', '+233', 'Ghanaian cedi', 'GHS', '₵', 2],
            ['Greece', '+30', 'Euro', 'EUR', '€', 2],
            ['Grenada', '+1473', 'Eastern Caribbean dollar', 'XCD', '$', 2],
            ['Guatemala', '+502', 'Guatemalan quetzal', 'GTQ', 'Q', 2],
            ['Guinea', '+224', 'Guinean franc', 'GNF', 'Fr', 0],
            ['Guinea-Bissau', '+245', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Guyana', '+592', 'Guyanese dollar', 'GYD', '$', 2],
            ['Haiti', '+509', 'Haitian gourde', 'HTG', 'G', 2],
            ['Honduras', '+504', 'Honduran lempira', 'HNL', 'L', 2],
            ['Hungary', '+36', 'Hungarian forint', 'HUF', 'Ft', 2],
            ['Iceland', '+354', 'Icelandic króna', 'ISK', 'kr', 0],
            ['India', '+91', 'Indian rupee', 'INR', '₹', 2],
            ['Indonesia', '+62', 'Indonesian rupiah', 'IDR', 'Rp', 2],
            ['Iran', '+98', 'Iranian rial', 'IRR', '﷼', 2],
            ['Iraq', '+964', 'Iraqi dinar', 'IQD', 'ع.د', 3],
            ['Ireland', '+353', 'Euro', 'EUR', '€', 2],
            ['Israel', '+972', 'Israeli new shekel', 'ILS', '₪', 2],
            ['Italy', '+39', 'Euro', 'EUR', '€', 2],
            ['Ivory Coast', '+225', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Jamaica', '+1876', 'Jamaican dollar', 'JMD', '$', 2],
            ['Japan', '+81', 'Japanese yen', 'JPY', '¥', 0],
            ['Jordan', '+962', 'Jordanian dinar', 'JOD', 'د.ا', 3],
            ['Kazakhstan', '+7', 'Kazakhstani tenge', 'KZT', '₸', 2],
            ['Kenya', '+254', 'Kenyan shilling', 'KES', 'Sh', 2],
            ['Kiribati', '+686', 'Australian dollar', 'AUD', '$', 2],
            ['Kuwait', '+965', 'Kuwaiti dinar', 'KWD', 'د.ك', 3],
            ['Kyrgyzstan', '+996', 'Kyrgyzstani som', 'KGS', 'с', 2],
            ['Laos', '+856', 'Lao kip', 'LAK', '₭', 2],
            ['Latvia', '+371', 'Euro', 'EUR', '€', 2],
            ['Lebanon', '+961', 'Lebanese pound', 'LBP', 'ل.ل', 2],
            ['Lesotho', '+266', 'Lesotho loti', 'LSL', 'L', 2],
            ['Liberia', '+231', 'Liberian dollar', 'LRD', '$', 2],
            ['Libya', '+218', 'Libyan dinar', 'LYD', 'ل.د', 3],
            ['Liechtenstein', '+423', 'Swiss franc', 'CHF', 'Fr', 2],
            ['Lithuania', '+370', 'Euro', 'EUR', '€', 2],
            ['Luxembourg', '+352', 'Euro', 'EUR', '€', 2],
            ['Madagascar', '+261', 'Malagasy ariary', 'MGA', 'Ar', 2],
            ['Malawi', '+265', 'Malawian kwacha', 'MWK', 'MK', 2],
            ['Malaysia', '+60', 'Malaysian ringgit', 'MYR', 'RM', 2],
            ['Maldives', '+960', 'Maldivian rufiyaa', 'MVR', '.ރ', 2],
            ['Mali', '+223', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Malta', '+356', 'Euro', 'EUR', '€', 2],
            ['Marshall Islands', '+692', 'United States dollar', 'USD', '$', 2],
            ['Mauritania', '+222', 'Mauritanian ouguiya', 'MRU', 'UM', 2],
            ['Mauritius', '+230', 'Mauritian rupee', 'MUR', '₨', 2],
            ['Mexico', '+52', 'Mexican peso', 'MXN', '$', 2],
            ['Micronesia', '+691', 'United States dollar', 'USD', '$', 2],
            ['Moldova', '+373', 'Moldovan leu', 'MDL', 'L', 2],
            ['Monaco', '+377', 'Euro', 'EUR', '€', 2],
            ['Mongolia', '+976', 'Mongolian tögrög', 'MNT', '₮', 2],
            ['Montenegro', '+382', 'Euro', 'EUR', '€', 2],
            ['Morocco', '+212', 'Moroccan dirham', 'MAD', 'د.م.', 2],
            ['Mozambique', '+258', 'Mozambican metical', 'MZN', 'MT', 2],
            ['Myanmar', '+95', 'Burmese kyat', 'MMK', 'Ks', 2],
            ['Namibia', '+264', 'Namibian dollar', 'NAD', '$', 2],
            ['Nauru', '+674', 'Australian dollar', 'AUD', '$', 2],
            ['Nepal', '+977', 'Nepalese rupee', 'NPR', '₨', 2],
            ['Netherlands', '+31', 'Euro', 'EUR', '€', 2],
            ['New Zealand', '+64', 'New Zealand dollar', 'NZD', '$', 2],
            ['Nicaragua', '+505', 'Nicaraguan córdoba', 'NIO', 'C$', 2],
            ['Niger', '+227', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Nigeria', '+234', 'Nigerian naira', 'NGN', '₦', 2],
            ['North Korea', '+850', 'North Korean won', 'KPW', '₩', 2],
            ['North Macedonia', '+389', 'denar', 'MKD', 'den', 2],
            ['Norway', '+47', 'Norwegian krone', 'NOK', 'kr', 2],
            ['Oman', '+968', 'Omani rial', 'OMR', 'ر.ع.', 3],
            ['Pakistan', '+92', 'Pakistani rupee', 'PKR', '₨', 2],
            ['Palau', '+680', 'United States dollar', 'USD', '$', 2],
            ['Palestine', '+970', 'Israeli new shekel', 'ILS', '₪', 2],
            ['Panama', '+507', 'Panamanian balboa', 'PAB', 'B/.', 2],
            ['Papua New Guinea', '+675', 'Papua New Guinean kina', 'PGK', 'K', 2],
            ['Paraguay', '+595', 'Paraguayan guaraní', 'PYG', '₲', 0],
            ['Peru', '+51', 'Peruvian sol', 'PEN', 'S/.', 2],
            ['Philippines', '+63', 'Philippine peso', 'PHP', '₱', 2],
            ['Poland', '+48', 'Polish złoty', 'PLN', 'zł', 2],
            ['Portugal', '+351', 'Euro', 'EUR', '€', 2],
            ['Qatar', '+974', 'Qatari riyal', 'QAR', 'ر.ق', 2],
            ['Romania', '+40', 'Romanian leu', 'RON', 'lei', 2],
            ['Russia', '+7', 'Russian ruble', 'RUB', '₽', 2],
            ['Rwanda', '+250', 'Rwandan franc', 'RWF', 'Fr', 0],
            ['Saint Kitts and Nevis', '+1869', 'Eastern Caribbean dollar', 'XCD', '$', 2],
            ['Saint Lucia', '+1758', 'Eastern Caribbean dollar', 'XCD', '$', 2],
            ['Saint Vincent and the Grenadines', '+1784', 'Eastern Caribbean dollar', 'XCD', '$', 2],
            ['Samoa', '+685', 'Samoan tālā', 'WST', 'T', 2],
            ['San Marino', '+378', 'Euro', 'EUR', '€', 2],
            ['Saudi Arabia', '+966', 'Saudi riyal', 'SAR', 'ر.س', 2],
            ['Senegal', '+221', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Serbia', '+381', 'Serbian dinar', 'RSD', 'дин.', 2],
            ['Seychelles', '+248', 'Seychellois rupee', 'SCR', '₨', 2],
            ['Sierra Leone', '+232', 'Sierra Leonean leone', 'SLE', 'Le', 2],
            ['Singapore', '+65', 'Singapore dollar', 'SGD', '$', 2],
            ['Slovakia', '+421', 'Euro', 'EUR', '€', 2],
            ['Slovenia', '+386', 'Euro', 'EUR', '€', 2],
            ['Solomon Islands', '+677', 'Solomon Islands dollar', 'SBD', '$', 2],
            ['Somalia', '+252', 'Somali shilling', 'SOS', 'Sh', 2],
            ['South Africa', '+27', 'South African rand', 'ZAR', 'R', 2],
            ['South Korea', '+82', 'South Korean won', 'KRW', '₩', 0],
            ['South Sudan', '+211', 'South Sudanese pound', 'SSP', '£', 2],
            ['Spain', '+34', 'Euro', 'EUR', '€', 2],
            ['Sri Lanka', '+94', 'Sri Lankan rupee', 'LKR', 'Rs රු', 2],
            ['Sudan', '+249', 'Sudanese pound', 'SDG', 'PT', 2],
            ['Suriname', '+597', 'Surinamese dollar', 'SRD', '$', 2],
            ['Sweden', '+46', 'Swedish krona', 'SEK', 'kr', 2],
            ['Switzerland', '+41', 'Swiss franc', 'CHF', 'Fr.', 2],
            ['Syria', '+963', 'Syrian pound', 'SYP', '£', 2],
            ['São Tomé and Príncipe', '+239', 'São Tomé and Príncipe dobra', 'STN', 'Db', 2],
            ['Tajikistan', '+992', 'Tajikistani somoni', 'TJS', 'ЅМ', 2],
            ['Tanzania', '+255', 'Tanzanian shilling', 'TZS', 'Sh', 2],
            ['Thailand', '+66', 'Thai baht', 'THB', '฿', 2],
            ['Timor-Leste', '+670', 'United States dollar', 'USD', '$', 2],
            ['Togo', '+228', 'West African CFA franc', 'XOF', 'Fr', 0],
            ['Tonga', '+676', 'Tongan paʻanga', 'TOP', 'T$', 2],
            ['Trinidad and Tobago', '+1868', 'Trinidad and Tobago dollar', 'TTD', '$', 2],
            ['Tunisia', '+216', 'Tunisian dinar', 'TND', 'د.ت', 3],
            ['Turkmenistan', '+993', 'Turkmenistan manat', 'TMT', 'm', 2],
            ['Tuvalu', '+688', 'Australian dollar', 'AUD', '$', 2],
            ['Türkiye', '+90', 'Turkish lira', 'TRY', '₺', 2],
            ['Uganda', '+256', 'Ugandan shilling', 'UGX', 'Sh', 0],
            ['Ukraine', '+380', 'Ukrainian hryvnia', 'UAH', '₴', 2],
            ['United Arab Emirates', '+971', 'United Arab Emirates dirham', 'AED', 'د.إ', 2],
            ['United Kingdom', '+44', 'British pound', 'GBP', '£', 2],
            ['United States', '+1', 'United States dollar', 'USD', '$', 2],
            ['Uruguay', '+598', 'Uruguayan peso', 'UYU', '$', 2],
            ['Uzbekistan', '+998', 'Uzbekistani soʻm', 'UZS', 'so\'m', 2],
            ['Vanuatu', '+678', 'Vanuatu vatu', 'VUV', 'Vt', 0],
            ['Vatican City', '+39', 'Euro', 'EUR', '€', 2],
            ['Venezuela', '+58', 'Venezuelan bolívar soberano', 'VES', 'Bs.S.', 2],
            ['Vietnam', '+84', 'Vietnamese đồng', 'VND', '₫', 0],
            ['Yemen', '+967', 'Yemeni rial', 'YER', '﷼', 2],
            ['Zambia', '+260', 'Zambian kwacha', 'ZMW', 'ZK', 2],
            ['Zimbabwe', '+263', 'Zimbabwe Gold', 'ZWG', 'ZiG', 2],
        ];

        foreach ($countries as [$name, $phoneCode, $currencyName, $currency, $currencySymbol, $currencyDigit]) {
            Country::updateOrCreate(
                [
                    'name' => $name,
                    'deleted' => 0,
                ],
                [
                    'phone_code' => $phoneCode,
                    'currency_name' => $currencyName,
                    'currency' => $currency,
                    'currency_symbol' => $currencySymbol,
                    'default_currency_digit' => $currencyDigit,
                    'status' => 1,
                ],
            );
        }
    }
}

